plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ledgerbridge'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.web3j:core:4.14.0'
    implementation 'org.web3j:codegen:4.14.0'
    
    implementation 'software.amazon.awssdk:sqs:2.37.5'

    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('generateContractWrappers', JavaExec) {
    group = 'blockchain'
    description = 'Generate Java wrappers from Solidity ABI and BIN'

    classpath = configurations.runtimeClasspath
    mainClass = 'org.web3j.codegen.SolidityFunctionWrapperGenerator'

    args(
        '-a', '../../blockchain/build/SettlementLedger.abi',
        '-b', '../../blockchain/build/SettlementLedger.bin',
        '-o', '../../blockchain/generated',
        '-p', 'com.ledgerbridge.settlement.blockchain.generated'
    )
}

tasks.register('runSettlementLedgerDeployer', JavaExec) {
    group = 'blockchain'
    description = 'Deploy SettlementLedger to the local Besu network'

    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.ledgerbridge.settlement.blockchain.SettlementLedgerDeployer'
}

sourceSets {
    main {
        java {
            srcDirs += '../../blockchain/generated'
        }
    }
}